apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - name: events
        image: localhost:5000/events:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
spec:
  selector:
    app: events
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort


